# Generated by Django 4.2.5 on 2023-11-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
